# Generated by Django 5.0.2 on 2024-06-21 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_detail_user_data1_userid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail_user_data1',
            name='name',
        ),
        migrations.RemoveField(
            model_name='detail_user_data1',
            name='password',
        ),
        migrations.RemoveField(
            model_name='detail_user_data1',
            name='userid',
        ),
        migrations.AddField(
            model_name='detail_user_data1',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
