# Generated by Django 5.0.2 on 2024-06-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_detail_user_data1_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptom',
            name='diet',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='medication',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='precautions',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='symptoms',
            field=models.TextField(default=[], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='workout',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
