# Generated by Django 4.2 on 2024-06-25 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_symptom_diet_alter_symptom_medication_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptom',
            name='symptoms',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
